GET http://localhost:3000

### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "ammar2@gmail.com",
    "password" : "11111111"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username" : "ammar@gmail.com",
    "password" : "11111111"
}
### add task
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzcwODIxNTcwLCJleHAiOjE3NzA5MDc5NzB9.gYn56KKnkmnOZm-kp_47OB4kluO3rjiDNtkStysD3eA

{
    "task" : "finish the course" 
}